{{- if .Values.Kubernetes -}}
{{- if .Values.fluentbit.enable -}}
{{- if .Values.fluentbit.output.opensearch -}}
apiVersion: v1
data:
  password: admin
  username: admin
kind: Secret
metadata:
  name: opensearch-credentials
  namespace: {{ template "kubeSphere-logging.namespace" . }}
type: kubernetes.io/basic-auth
{{- end }}
{{- end }}
{{- end }}
